imports:
  - { resource: get_handler.yaml }
  - { resource: put_handler.yaml }
  - { resource: post_handler.yaml }
  - { resource: patch_handler.yaml }

services:
  deserialize_param_converter:
    public: true
    class: Lores\RestParamConverterBundle\Component\ParamConverter\ChainedParamConverter
    autowire: false
    arguments:
      - '@post_handler'
    tags:
      - { name: request.param_converter, priority: -100, converter: deserialize_param_converter }

  fetch_param_converter:
    public: true
    class: Lores\RestParamConverterBundle\Component\ParamConverter\ChainedParamConverter
    autowire: false
    arguments:
      - '@get_handler'
    tags:
      - { name: request.param_converter,  priority: -100, converter: fetch_param_converter }

  get_param_converter:
    public: true
    class: Lores\RestParamConverterBundle\Component\ParamConverter\ByMethodParamConverter
    autowire: false
    arguments:
      - 'GET'
      - '@get_handler'
    tags:
      - { name: request.param_converter, priority: -1, converter: get_param_converter }

  delete_param_converter:
    public: true
    class: Lores\RestParamConverterBundle\Component\ParamConverter\ByMethodParamConverter
    autowire: false
    arguments:
      - 'DELETE'
      - '@get_handler'
    tags:
      - { name: request.param_converter, priority: -2, converter: delete_param_converter }

  post_param_converter:
    public: true
    class: Lores\RestParamConverterBundle\Component\ParamConverter\ByMethodParamConverter
    autowire: false
    arguments:
      - 'POST'
      - '@post_handler'
    tags:
      - { name: request.param_converter, priority: -3, converter: post_param_converter }

  put_param_converter:
    public: true
    class: Lores\RestParamConverterBundle\Component\ParamConverter\ByMethodParamConverter
    autowire: false
    arguments:
      - 'PUT'
      - '@put_handler'
    tags:
      - { name: request.param_converter, priority: -4, converter: put_param_converter }

  patch_param_converter:
    public: true
    class: Lores\RestParamConverterBundle\Component\ParamConverter\ByMethodParamConverter
    autowire: false
    arguments:
      - 'PATCH'
      - '@patch_handler'
    tags:
      - { name: request.param_converter, priority: -5, converter: patch_param_converter }

  context_factory:
    class: Lores\RestParamConverterBundle\Component\JMS\SkipDoctrineContextFactory
    arguments:
      - '@doctrine.orm.default_entity_manager'